version: "3.3"
name: my-project-name

services:
    mysql:
        image: mariadb:latest
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        networks:
            - internal
    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        networks:
            - internal

secrets:
    my_secret:
        file: .env

networks:
    internal:
        name: internal
